export const FILTER_ALL_COMPANIES = 'All Companies'

export const SORT_FIRST_NAME_DESC = 'First Name, Descending'
export const SORT_FIRST_NAME_ASC = 'First Name, Ascending'
export const SORT_LAST_NAME_DESC = 'Last Name, Descending'
export const SORT_LAST_NAME_ASC = 'Last Name, Ascending'
export const SORT_COMPANY_NAME_DESC = 'Company Name, Descending'
export const SORT_COMPANY_NAME_ASC = 'Company Name, Ascending'

export const SORT_FIRST_NAME_DESC_CODE = 'firstname|desc'
export const SORT_FIRST_NAME_ASC_CODE = 'firstname|asc'
export const SORT_LAST_NAME_DESC_CODE = 'lastname|desc'
export const SORT_LAST_NAME_ASC_CODE = 'lastname|asc'
export const SORT_COMPANY_NAME_DESC_CODE = 'companyname|desc'
export const SORT_COMPANY_NAME_ASC_CODE = 'companyname|asc'
